[package]
name = "rad"
version = "0.1.0"
authors = ["Fintan Halpenny fintan.halpenny@gmail.com"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
rad-exe = "0"
tokio = "1.1"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
