steps:
  - label: "Build + Test"
    commands:
      - ".ci/build-test"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-bins-build@sha256:a7bcc14741e290f4a35b42de055ba62f4908870f145570acc88fe265410ca0c2"
      DOCKER_FILE: .docker/build/Dockerfile

  - label: "Clippy Yeah Yeah Clippy Shlippy Yeah"
    commands:
      - ".ci/clippy"
    agents: *build-agent
    env: *build-docker

  - label: "Deny"
    commands:
      - ".ci/advisory"
    agents: *build-agent
    env: *build-docker

  - label: "Docs"
    commands:
      - ".ci/docs"
    agents: *build-agent
    env: *build-docker

  - label: "Seed Docker Image"
    commands:
      - ".ci/docker-seed"
    agents: *build-agent
    env:
      <<: *build-docker
      STEP_DOCKER_FILE: .docker/seed/Dockerfile
      STEP_DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-seed-node

  - label: "Dist"
    commands:
      - ".ci/bins"
      - ".ci/ui"
      - "infra/scripts/dist.sh"
    agents: *build-agent
    env: *build-docker
    artifact_paths:
      - "dist/*"
