#!/usr/bin/env bash
set -eou pipefail

source "$(dirname ${BASH_SOURCE[0]})/.env"

echo '--- Formatting'
cargo fmt -- --check

echo '--- Clippy'
cargo clippy --all-targets --all-features -- -D warnings
