#!/usr/bin/env bash
set -eou pipefail

source "$(dirname ${BASH_SOURCE[0]})/.env"

if [[ "${BUILDKITE_BRANCH:-}" == "master" ]]; then
    echo "--- Preparing release build"
    cargo build -p radicle-seed-node --release

    echo "--- Copying build artifact"
    cp ./target/release/radicle-seed-node .docker/seed/radicle-seed-node
else
    echo "--- Preparing debug build"
    cargo build -p radicle-seed-node

    echo "--- Copying build artifact"
    cp ./target/debug/radicle-seed-node .docker/seed/radicle-seed-node
fi

